// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180518085305_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Data1", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("EntityId");

                    b.HasKey("Id");

                    b.ToTable("Data1s");
                });

            modelBuilder.Entity("Data.Data2", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("EntityId");

                    b.HasKey("Id");

                    b.ToTable("Data2s");
                });

            modelBuilder.Entity("Data.Data3", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("EntityId");

                    b.HasKey("Id");

                    b.ToTable("Data3s");
                });

            modelBuilder.Entity("Data.Data1", b =>
                {
                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueBool", "Prop1", b1 =>
                        {
                            b1.Property<long>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop1_Source")
                                .HasMaxLength(64);

                            b1.Property<bool?>("Value")
                                .HasColumnName("Prop1");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop1")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueBool", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop15", b1 =>
                        {
                            b1.Property<long?>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop15_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop15")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop15")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop17", b1 =>
                        {
                            b1.Property<long?>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop17_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop17")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop17")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop19", b1 =>
                        {
                            b1.Property<long?>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop19_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop19")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop19")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop2", b1 =>
                        {
                            b1.Property<long>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop2_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop2")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop2")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop20", b1 =>
                        {
                            b1.Property<long?>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop20_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop20")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop20")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop3", b1 =>
                        {
                            b1.Property<long>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop3_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop3")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop3")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop7", b1 =>
                        {
                            b1.Property<long?>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop7_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop7")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop7")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Prop10", b1 =>
                        {
                            b1.Property<long>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop10_Source")
                                .HasMaxLength(64);

                            b1.Property<decimal?>("Value")
                                .HasColumnName("Prop10")
                                .HasColumnType("decimal(32,12)");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop10")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Prop13", b1 =>
                        {
                            b1.Property<long?>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop13_Source")
                                .HasMaxLength(64);

                            b1.Property<decimal?>("Value")
                                .HasColumnName("Prop13")
                                .HasColumnType("decimal(32,12)");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop13")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Prop16", b1 =>
                        {
                            b1.Property<long?>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop16_Source")
                                .HasMaxLength(64);

                            b1.Property<decimal?>("Value")
                                .HasColumnName("Prop16")
                                .HasColumnType("decimal(32,12)");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop16")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Prop8", b1 =>
                        {
                            b1.Property<long>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop8_Source")
                                .HasMaxLength(64);

                            b1.Property<decimal?>("Value")
                                .HasColumnName("Prop8")
                                .HasColumnType("decimal(32,12)");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop8")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop12", b1 =>
                        {
                            b1.Property<long?>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop12_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop12");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop12")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop18", b1 =>
                        {
                            b1.Property<long?>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop18_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop18");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop18")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop4", b1 =>
                        {
                            b1.Property<long>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop4_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop4");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop4")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop5", b1 =>
                        {
                            b1.Property<long>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop5_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop5");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop5")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop9", b1 =>
                        {
                            b1.Property<long?>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop9_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop9");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop9")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Prop11", b1 =>
                        {
                            b1.Property<long>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop11_Source")
                                .HasMaxLength(64);

                            b1.Property<int?>("Value")
                                .HasColumnName("Prop11");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop11")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Prop14", b1 =>
                        {
                            b1.Property<long?>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop14_Source")
                                .HasMaxLength(64);

                            b1.Property<int?>("Value")
                                .HasColumnName("Prop14");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop14")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Prop6", b1 =>
                        {
                            b1.Property<long>("Data1Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop6_Source")
                                .HasMaxLength(64);

                            b1.Property<int?>("Value")
                                .HasColumnName("Prop6");

                            b1.ToTable("Data1s");

                            b1.HasOne("Data.Data1")
                                .WithOne("Prop6")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Data1Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Data.Data2", b =>
                {
                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueBool", "Prop1", b1 =>
                        {
                            b1.Property<long>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop1_Source")
                                .HasMaxLength(64);

                            b1.Property<bool?>("Value")
                                .HasColumnName("Prop1");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop1")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueBool", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop15", b1 =>
                        {
                            b1.Property<long?>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop15_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop15")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop15")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop17", b1 =>
                        {
                            b1.Property<long?>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop17_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop17")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop17")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop19", b1 =>
                        {
                            b1.Property<long?>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop19_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop19")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop19")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop2", b1 =>
                        {
                            b1.Property<long?>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop2_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop2")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop2")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop20", b1 =>
                        {
                            b1.Property<long?>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop20_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop20")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop20")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop3", b1 =>
                        {
                            b1.Property<long?>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop3_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop3")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop3")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop7", b1 =>
                        {
                            b1.Property<long?>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop7_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop7")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop7")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Prop10", b1 =>
                        {
                            b1.Property<long>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop10_Source")
                                .HasMaxLength(64);

                            b1.Property<decimal?>("Value")
                                .HasColumnName("Prop10")
                                .HasColumnType("decimal(32,12)");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop10")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Prop13", b1 =>
                        {
                            b1.Property<long>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop13_Source")
                                .HasMaxLength(64);

                            b1.Property<decimal?>("Value")
                                .HasColumnName("Prop13")
                                .HasColumnType("decimal(32,12)");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop13")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Prop16", b1 =>
                        {
                            b1.Property<long>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop16_Source")
                                .HasMaxLength(64);

                            b1.Property<decimal?>("Value")
                                .HasColumnName("Prop16")
                                .HasColumnType("decimal(32,12)");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop16")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Prop8", b1 =>
                        {
                            b1.Property<long>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop8_Source")
                                .HasMaxLength(64);

                            b1.Property<decimal?>("Value")
                                .HasColumnName("Prop8")
                                .HasColumnType("decimal(32,12)");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop8")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop12", b1 =>
                        {
                            b1.Property<long?>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop12_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop12");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop12")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop18", b1 =>
                        {
                            b1.Property<long?>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop18_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop18");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop18")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop4", b1 =>
                        {
                            b1.Property<long?>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop4_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop4");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop4")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop5", b1 =>
                        {
                            b1.Property<long?>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop5_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop5");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop5")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop9", b1 =>
                        {
                            b1.Property<long?>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop9_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop9");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop9")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Prop11", b1 =>
                        {
                            b1.Property<long>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop11_Source")
                                .HasMaxLength(64);

                            b1.Property<int?>("Value")
                                .HasColumnName("Prop11");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop11")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Prop14", b1 =>
                        {
                            b1.Property<long>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop14_Source")
                                .HasMaxLength(64);

                            b1.Property<int?>("Value")
                                .HasColumnName("Prop14");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop14")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Prop6", b1 =>
                        {
                            b1.Property<long>("Data2Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop6_Source")
                                .HasMaxLength(64);

                            b1.Property<int?>("Value")
                                .HasColumnName("Prop6");

                            b1.ToTable("Data2s");

                            b1.HasOne("Data.Data2")
                                .WithOne("Prop6")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Data2Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("Data.Data3", b =>
                {
                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueBool", "Prop1", b1 =>
                        {
                            b1.Property<long>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop1_Source")
                                .HasMaxLength(64);

                            b1.Property<bool?>("Value")
                                .HasColumnName("Prop1");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop1")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueBool", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop15", b1 =>
                        {
                            b1.Property<long?>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop15_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop15")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop15")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop17", b1 =>
                        {
                            b1.Property<long?>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop17_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop17")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop17")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop19", b1 =>
                        {
                            b1.Property<long?>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop19_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop19")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop19")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop2", b1 =>
                        {
                            b1.Property<long?>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop2_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop2")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop2")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop20", b1 =>
                        {
                            b1.Property<long?>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop20_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop20")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop20")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop3", b1 =>
                        {
                            b1.Property<long?>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop3_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop3")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop3")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Prop7", b1 =>
                        {
                            b1.Property<long?>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop7_Source")
                                .HasMaxLength(64);

                            b1.Property<DateTime?>("Value")
                                .HasColumnName("Prop7")
                                .HasColumnType("datetime2");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop7")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDateTime", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Prop10", b1 =>
                        {
                            b1.Property<long>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop10_Source")
                                .HasMaxLength(64);

                            b1.Property<decimal?>("Value")
                                .HasColumnName("Prop10")
                                .HasColumnType("decimal(32,12)");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop10")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Prop13", b1 =>
                        {
                            b1.Property<long>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop13_Source")
                                .HasMaxLength(64);

                            b1.Property<decimal?>("Value")
                                .HasColumnName("Prop13")
                                .HasColumnType("decimal(32,12)");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop13")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Prop16", b1 =>
                        {
                            b1.Property<long>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop16_Source")
                                .HasMaxLength(64);

                            b1.Property<decimal?>("Value")
                                .HasColumnName("Prop16")
                                .HasColumnType("decimal(32,12)");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop16")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Prop8", b1 =>
                        {
                            b1.Property<long>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop8_Source")
                                .HasMaxLength(64);

                            b1.Property<decimal?>("Value")
                                .HasColumnName("Prop8")
                                .HasColumnType("decimal(32,12)");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop8")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDecimal", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop12", b1 =>
                        {
                            b1.Property<long?>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop12_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop12");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop12")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop18", b1 =>
                        {
                            b1.Property<long?>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop18_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop18");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop18")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop4", b1 =>
                        {
                            b1.Property<long?>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop4_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop4");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop4")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop5", b1 =>
                        {
                            b1.Property<long?>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop5_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop5");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop5")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Prop9", b1 =>
                        {
                            b1.Property<long?>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop9_Source")
                                .HasMaxLength(64);

                            b1.Property<double?>("Value")
                                .HasColumnName("Prop9");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop9")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueDouble", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Prop11", b1 =>
                        {
                            b1.Property<long>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop11_Source")
                                .HasMaxLength(64);

                            b1.Property<int?>("Value")
                                .HasColumnName("Prop11");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop11")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Prop14", b1 =>
                        {
                            b1.Property<long>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop14_Source")
                                .HasMaxLength(64);

                            b1.Property<int?>("Value")
                                .HasColumnName("Prop14");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop14")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Prop6", b1 =>
                        {
                            b1.Property<long>("Data3Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Source")
                                .HasColumnName("Prop6_Source")
                                .HasMaxLength(64);

                            b1.Property<int?>("Value")
                                .HasColumnName("Prop6");

                            b1.ToTable("Data3s");

                            b1.HasOne("Data.Data3")
                                .WithOne("Prop6")
                                .HasForeignKey("GDB.Vinn.DataWarehouse.DataSets.ComplexTypes.ReferenceValueInteger", "Data3Id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
