// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180518091854_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Data1", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("EntityId");

                    b.Property<bool>("Prop1");

                    b.Property<decimal>("Prop10");

                    b.Property<string>("Prop10Source");

                    b.Property<int>("Prop11");

                    b.Property<string>("Prop11Source");

                    b.Property<double>("Prop12");

                    b.Property<string>("Prop12Source");

                    b.Property<decimal>("Prop13");

                    b.Property<decimal>("Prop13Source");

                    b.Property<int>("Prop14");

                    b.Property<string>("Prop14Source");

                    b.Property<DateTime>("Prop15");

                    b.Property<string>("Prop15Source");

                    b.Property<decimal>("Prop16");

                    b.Property<string>("Prop16Source");

                    b.Property<DateTime>("Prop17");

                    b.Property<string>("Prop17Source");

                    b.Property<double>("Prop18");

                    b.Property<string>("Prop18Source");

                    b.Property<DateTime>("Prop19");

                    b.Property<string>("Prop19Source");

                    b.Property<string>("Prop1Source");

                    b.Property<DateTime>("Prop2");

                    b.Property<DateTime>("Prop20");

                    b.Property<string>("Prop20Source");

                    b.Property<string>("Prop2Source");

                    b.Property<DateTime>("Prop3");

                    b.Property<string>("Prop3Source");

                    b.Property<double>("Prop4");

                    b.Property<string>("Prop4Source");

                    b.Property<double>("Prop5");

                    b.Property<string>("Prop5Source");

                    b.Property<int>("Prop6");

                    b.Property<string>("Prop6Source");

                    b.Property<DateTime>("Prop7");

                    b.Property<string>("Prop7Source");

                    b.Property<decimal>("Prop8");

                    b.Property<string>("Prop8Source");

                    b.Property<double>("Prop9");

                    b.Property<string>("Prop9Source");

                    b.HasKey("Id");

                    b.ToTable("Data1s");
                });

            modelBuilder.Entity("Data.Data2", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("EntityId");

                    b.Property<bool>("Prop1");

                    b.Property<decimal>("Prop10");

                    b.Property<string>("Prop10Source");

                    b.Property<int>("Prop11");

                    b.Property<string>("Prop11Source");

                    b.Property<double>("Prop12");

                    b.Property<string>("Prop12Source");

                    b.Property<decimal>("Prop13");

                    b.Property<decimal>("Prop13Source");

                    b.Property<int>("Prop14");

                    b.Property<string>("Prop14Source");

                    b.Property<DateTime>("Prop15");

                    b.Property<string>("Prop15Source");

                    b.Property<decimal>("Prop16");

                    b.Property<string>("Prop16Source");

                    b.Property<DateTime>("Prop17");

                    b.Property<string>("Prop17Source");

                    b.Property<double>("Prop18");

                    b.Property<string>("Prop18Source");

                    b.Property<DateTime>("Prop19");

                    b.Property<string>("Prop19Source");

                    b.Property<string>("Prop1Source");

                    b.Property<DateTime>("Prop2");

                    b.Property<DateTime>("Prop20");

                    b.Property<string>("Prop20Source");

                    b.Property<string>("Prop2Source");

                    b.Property<DateTime>("Prop3");

                    b.Property<string>("Prop3Source");

                    b.Property<double>("Prop4");

                    b.Property<string>("Prop4Source");

                    b.Property<double>("Prop5");

                    b.Property<string>("Prop5Source");

                    b.Property<int>("Prop6");

                    b.Property<string>("Prop6Source");

                    b.Property<DateTime>("Prop7");

                    b.Property<string>("Prop7Source");

                    b.Property<decimal>("Prop8");

                    b.Property<string>("Prop8Source");

                    b.Property<double>("Prop9");

                    b.Property<string>("Prop9Source");

                    b.HasKey("Id");

                    b.ToTable("Data2s");
                });

            modelBuilder.Entity("Data.Data3", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("EntityId");

                    b.Property<bool>("Prop1");

                    b.Property<decimal>("Prop10");

                    b.Property<string>("Prop10Source");

                    b.Property<int>("Prop11");

                    b.Property<string>("Prop11Source");

                    b.Property<double>("Prop12");

                    b.Property<string>("Prop12Source");

                    b.Property<decimal>("Prop13");

                    b.Property<decimal>("Prop13Source");

                    b.Property<int>("Prop14");

                    b.Property<string>("Prop14Source");

                    b.Property<DateTime>("Prop15");

                    b.Property<string>("Prop15Source");

                    b.Property<decimal>("Prop16");

                    b.Property<string>("Prop16Source");

                    b.Property<DateTime>("Prop17");

                    b.Property<string>("Prop17Source");

                    b.Property<double>("Prop18");

                    b.Property<string>("Prop18Source");

                    b.Property<DateTime>("Prop19");

                    b.Property<string>("Prop19Source");

                    b.Property<string>("Prop1Source");

                    b.Property<DateTime>("Prop2");

                    b.Property<DateTime>("Prop20");

                    b.Property<string>("Prop20Source");

                    b.Property<string>("Prop2Source");

                    b.Property<DateTime>("Prop3");

                    b.Property<string>("Prop3Source");

                    b.Property<double>("Prop4");

                    b.Property<string>("Prop4Source");

                    b.Property<double>("Prop5");

                    b.Property<string>("Prop5Source");

                    b.Property<int>("Prop6");

                    b.Property<string>("Prop6Source");

                    b.Property<DateTime>("Prop7");

                    b.Property<string>("Prop7Source");

                    b.Property<decimal>("Prop8");

                    b.Property<string>("Prop8Source");

                    b.Property<double>("Prop9");

                    b.Property<string>("Prop9Source");

                    b.HasKey("Id");

                    b.ToTable("Data3s");
                });
#pragma warning restore 612, 618
        }
    }
}
